### ISSUE TITLE
Add support for Dependency Injection

### ISSUE THREAD

**Issue by Kralizek** [neuecc/DatadogSharp#1]
Both `DatadogStats` and `TracingManager` use a Singleton approach but it makes very difficult to test classes using this library requiring the usage of an (unnecessary) adapter class.

If it's welcome, I can work on a PR to solve the issue.

**Comment by neuecc** [comment]
I've merged your pull request and upload `1.5.3` on NuGet, thanks.

**Comment by Kralizek** [comment]
Thank you for the quick reply :)
