### ISSUE TITLE
APM( Tracing) on .NET Core

### ISSUE THREAD

**Issue by Vlaaaaaaad** [neuecc/DatadogSharp#3]
Hi,

Does this support tracing on .Net Core 2.0? If not is there an ETA for it?

Thank you!

**Comment by neuecc** [comment]
This library provides by .NET Standard 2.0, it supports .NET Core 2.0.

**Comment by neuecc** [comment]
You can use `TracingManager.SetExceptionLogger` for logging when send failed.

**Comment by Vlaaaaaaad** [comment]
Thank you very much for your answers!

Meanwhile I decided to wait for official Datadog support for .NET Core as we would have to reimplement quite a lot.

Closing this as it was solved( there is support even though I haven't tested it).
